FROM publicstake/cardano:1.24.2

COPY config.json /root/.cardano/config/
COPY mainnet-byron-genesis.json /root/.cardano/config/
COPY mainnet-shelley-genesis.json /root/.cardano/config/
COPY mainnet-db-sync-config.json /root/.cardano/config/